// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID         string
	CustomerID string
	FlightID   string
	SeatNumber sql.NullString
	CreatedAt  time.Time
}
