// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  id,
  customer_id,
  flight_id,
  seat_number 
) VALUES (
  ?, ?, ?, ?
) RETURNING id, customer_id, flight_id, seat_number, created_at
`

type CreateBookingParams struct {
	ID         string
	CustomerID string
	FlightID   string
	SeatNumber sql.NullString
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ID,
		arg.CustomerID,
		arg.FlightID,
		arg.SeatNumber,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FlightID,
		&i.SeatNumber,
		&i.CreatedAt,
	)
	return i, err
}
