// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const saveSeatAllocation = `-- name: SaveSeatAllocation :exec
INSERT INTO seat_allocations (
  id,
  flight_id,
  seat_number
) VALUES (
  ?, ?, ?
)
`

type SaveSeatAllocationParams struct {
	ID         string
	FlightID   string
	SeatNumber string
}

func (q *Queries) SaveSeatAllocation(ctx context.Context, arg SaveSeatAllocationParams) error {
	_, err := q.db.ExecContext(ctx, saveSeatAllocation, arg.ID, arg.FlightID, arg.SeatNumber)
	return err
}
